const mutationTypes = {
    SET_STATIONS: 'SET_STATIONS',
    SET_STOPS: 'SET_STOPS',
    SET_STOPS_INPUT_VALUE: 'SET_STOPS_INPUT_VALUE',
    SET_STATIONS_INPUT_VALUE: 'SET_STATIONS_INPUT_VALUE',
    SET_SELECTED_STATION_ID: 'SET_SELECTED_STATION_ID',
    SET_SELECTED_STOP_ID: 'SET_SELECTED_STOP_ID',
    SET_SELECTED_TYPE: 'SET_SELECTED_TYPE',
    SET_IS_LOADING: 'SET_IS_LOADING',
    SET_IS_ERROR: 'SET_IS_ERROR'
}
export default mutationTypes